### ISSUE TITLE
Option to only draw on desktop

### ISSUE THREAD

**Issue by emansom** [isjerryxiao/gnome-shell-extension-activate-gnome#5]
Allow toggling an option, possibly with the default being toggled, that allows only drawing on the desktop; as to remain in the perfect threshold of annoyance, like Windoze does.

Logic from the [`background-logo-extension`](https://pagure.io/background-logo-extension/tree/master) extension in Fedora can be re-used for this. Latest source can be found [here](https://pagure.io/background-logo-extension/tree/master), example of its usage [here](https://www.reddit.com/r/pop_os/comments/lilr3d/backgroundlogo_gnome_extension_from_fedora/).

**Comment by isjerryxiao** [comment]
Why would you want that? "Activate Windows" watermark does not work that way either.

**Comment by isjerryxiao** [comment]
Close due to inactivity.
